### ISSUE TITLE
Blocking Sprockets seeping in from gem dependencies

### ISSUE THREAD

**Issue by basicfeatures** [rails/propshaft#114]
I'm trying to `bundle add solidus && rails generate solidus:install` but it carries with it Sprockets which will automatically replace my app's Propshaft so that everything gets messed up. Is there a way to force blockage of Sprockets somehow?

**Comment by brenogazzola** [comment]
No, there's not. Best you can do is compare your app before and after the install and undo the sprockets changes. Then take a look at Propshaft's upgrade guide to see if you need to make any changes to Solidus assets for them to work correctly.

I'm closing this since it's not an issue, but feel free to keep commenting.

**Comment by basicfeatures** [comment]
I've removed all traces of Sprockets from my app itself. In that case I reckon the only way is to fork Solidus and try to remove all traces there.

Cheers!
