### ISSUE TITLE
How to refer to a font asset?

### ISSUE THREAD

**Issue by airblade** [rails/propshaft#36]
I've been trying out the new asset pipeline today:

- Rails 7 https://github.com/rails/rails/commit/63d71786b222455ea6a1ab5e7a4f97bd368d9b93
- propshaft 0.4.1
- cssbundling-rails 0.2.6 configured for Bulma
- (importmap-rails 0.9.1)

It's so fast compared to webpack :)

However I can't figure out how to refer to a font asset in a stylesheet.

Here's the directory structure:

```
app/assets/
├── builds/
│   └── application.css
├── config/
├── fonts/
│   └── susa-regular.woff2
├── images/
└── stylesheets/
    ├── application.bulma.sass
    └── fonts.sass
```

And here are the test stylesheets:

```sass
// app/assets/stylesheets/application.bulma.sass
@import 'fonts'
```

```sass
// app/assets/stylesheets/fonts.sass
@font-face
  font-family: 'SusaRegular'
  src: url('../fonts/susa-regular.woff2') format('woff2')

.logotype
  font-family: 'SusaRegular', serif
```

```html
<!-- html snippet ->
<p class="logotype">hello</p>
```

The `application.css` which is built by propshaft and/or cssbundling repeats the font-face's src declaration verbatim.  I had hoped it would replace it with a path to a digested copy of the font file.

So, unsurprisingly, when I load a page in the browser, there's a 404 for "GET http://0.0.0.0:3000/fonts/susa-regular.woff2".

I checked `Rails.application.config.assets.paths` in the Rails console; it includes my `app/assets/fonts/` directory.

I tried using `asset-path(...)` instead of `url(...)`, but it didn't work (though I didn't expect to as I think it's obsolete?).

Any tips would be much appreciated.  Thank you!

**Comment by brenogazzola** [comment]
Propshaft will include each folder inside `app/assets` and precompile their contents to `public/assets`. This means that the file `app/assets/fonts/susa-regular.woff2` will be placed in `public/assets/susa-regular.woff2`. 

Could you try clobbering your assets and precompiling them again, to ensure that only propshaft's assets are in `public/assets`.

Also, whenever you are not sure of the location of your files, you can use `rake assets:revel` to get a full list of logical paths.

**Comment by brenogazzola** [comment]
You have another problem due to the `../` in your url. That will cause Propshaft to go one directory up from where `fonts.css` is, which is not what you want, because `fonts.scss` is already in the assets root.

Try this:
```css
@font-face
  font-family: 'SusaRegular'
  src: url('susa-regular.woff2') format('woff2')
```

Or this:
```css
@font-face
  font-family: 'SusaRegular'
  src: url('/susa-regular.woff2') format('woff2')
```

**Comment by airblade** [comment]
Interesting I don't have a `public/assets/` directory.  I'm running in `development` via `bin/dev` – not sure if that's relevant.

`rake assets:reveal` produces no output at all.

However I changed the font-face src url to `url('susa-regular.woff2')`, as you suggested, and it worked :)  Strangely I had already tried that without success.  This time I restarted the server; maybe that made a difference somehow.

I'm going to close this because you solved my problem – thank you.  But if you have time I'd be curious to hear more about `public/assets/` and `rake assets:reveal`.

**Comment by brenogazzola** [comment]
Propshaft has two ways of finding your assets (we call those `resolvers`). When you are developing and running `./bin/dev` you are using the `dynamic` resolver, which looks for your files in `app/assets`. 

When you deploy to your server you will run `rails assets:precompile` before restarting puma. This tells Propshaft to move all files from `app/assets` to `public/assets` and add digests to them so that CDNs can cache them properly. From that moment on, you are using the `static` resolver, which is much faster.

The task `rake assets:reveal` will show you every file in `public/assets`. This means that means that if you have not run `rails assets:precompile` yet, you are not going to see anything there.

**Comment by brenogazzola** [comment]
One thing you should be careful is that if you run `rails assets:precompile` and then `./bin/dev` Propshaft will use the `static` resolver, not the `dynamic` one. And since the `static` resolver reads files from `public/assets`, any change you make to your source files in `app/assets` will take an effect when you reload the page.

To solve that, run `rails assets:clobber`. It will remove all files from `public/assets` and force Propshaft back to the `dynamic` resolver.

**Comment by airblade** [comment]
Aha, that all makes sense.  Thank you for the clear explanations!  I appreciate it.

May I perhaps suggest a small update to the README, specifically feature no. 4?

```diff
- But it does offer a simple input->output compiler setup that by default is used to translate asset-path function calls in CSS to url(digested-asset) instead.
+ But it does offer a simple input->output compiler setup that by default is used to translate url(asset) calls in CSS to url(digested-asset) instead.
```
