### ISSUE TITLE
asset prefix / path

### ISSUE THREAD

**Issue by tabishiqbal** [rails/propshaft#51]
With sprockets you were able to change the prefix in `application.rb` to something like config.assets.prefix = "/assetz" so you're able to use `asset` as a model/routes etc is there a need for this using propshaft? if so how would you go about changing this?

**Comment by tabishiqbal** [comment]
Well for my application I wanted to use "Asset" for model/routes. Asset being a physical asset/item.  With sprockets I was able to change the prefix to something else and have asset.rb / controllers / views etc without having any conflicts and the asset pipeline working as expected.

**Comment by aaronjensen** [comment]
@brenogazzola what specifically does it disallow? It looks like it's a [configuration option](https://github.com/rails/propshaft/blob/785d42c3f3efcde18c87fd3f0ea433e41fc9da20/lib/propshaft/railtie.rb#L8). 

That said, we just tried to set it to `""` or `"/"` so that we can use our asset_host without a path prefix in production. Unfortunately, that causes propshaft to mount the server at `/`, which takes precedence over the other engine we have mounted. We don't need the propshaft server in production. So, for now, it seems like we are forced to use `assets.ourhost.com/assets/...`, is that correct?

Thanks!

**Comment by brenogazzola** [comment]
@aaronjensen OPS. Sorry, my bad. I'm so used to having an initializer to copy things from `app.config` to the railtie/engine `mattr_acessor` that I forgot Propshaft uses `app.config` to instantiate the Assembly. I'm not sure about the `asset_host` though. Never had to use it before, so I'm not aware how to works internally. I'll have to take some time to investigate how it works in Sprockets and try to replicate it in Propshaft. 

@tabishiqbal You @aaronjensen mentioned, you should be able to configure your path by using the line below in your environment files (`development.rb`, etc.)
```ruby
config.assets.prefix = "/my_path"
```

**Comment by aaronjensen** [comment]
@brenogazzola I don't know if it's right, but I would expect `config.public_file_server.enabled = false` to disable the propshaft server as well. Perhaps its own configuration would be warranted (`config.assets.server_enabled`?).

**Comment by rafaelfranca** [comment]
Is there any reason why the propshaft server is in production? In production the assets should be served by the CDN or by the `public_file_server` already embedded in Rails.

**Comment by dhh** [comment]
No reason to run the server in production, no.

**Comment by aaronjensen** [comment]
@dhh should it respect `config.public_file_server.enabled` or should it have its own setting?

**Comment by aaronjensen** [comment]
Works for me: https://github.com/rails/propshaft/pull/59

**Comment by aaronjensen** [comment]
I think this can be closed. Also, what's the plan for the next release? it'd be helpful for us to have the newly introduced config var. Thanks all.

**Comment by aaronjensen** [comment]
Thank you, @dhh
