### ISSUE TITLE
Upgrade documentation typo on Section 3

### ISSUE THREAD

**Issue by stevegeek** [rails/propshaft#76]
Hi! I was just following the [sprockets upgrade guide](https://github.com/rails/propshaft/blob/main/UPGRADING.md) and spotted a typo:

On Section 3, step 1, it says `Replace 'sass-rails' with 'propshaft';` - guess this should be `Replace 'sprockets-rails' with 'propshaft';`?

Also, in case its useful for future docs: 

while this guide is clearly about Sprockets -> propshaft, I was moving from a `webpacker` with no `sprockets-rails` setup, in which case if you first remove `webpacker` (Steps 1/2 on Section 1) it is not possible to run the `jsbundling-rails` install script on Step 3 as Rails will fail to boot with `NoMethodError: undefined method 'assets' for #<Rails::Application::Configuration` if the environment contains any `assets` config. So need to do the install before removing `webpacker` or add the sprockets railtie temporarily.

Just finished migrating a large app to `js/cssbundling-rails` & `propshaft` 🎉  Thanks!

**Comment by brenogazzola** [comment]
> On Section 3, step 1, it says `Replace 'sass-rails' with 'propshaft';` - guess this should be `Replace 'sprockets-rails' with 'propshaft';`?

Nope. It's really `sass-rails`. An app running the standard Sprockets for CSS, Webpacker for JS will have `sass-rails` in its Gemfile, not `sprockets-rails`.

> While this guide is clearly about Sprockets -> propshaft, I was moving from a webpacker with no sprockets-rails setup

We could use another upgrade guide, for someone who is fully on Webpacker, instead of Sprockets/Webpacker. Would you mind opening a PR for that? I think you could duplicate the current and remove things you didn't need, update the ones that were different, and add the ones that were not mentioned.

**Comment by stevegeek** [comment]
Thanks @brenogazzola , I see. OK sure, I have my notes from when I did the migration, I will flesh it out into a guide for review. In the mean time should I close this issue?
