### ISSUE TITLE
Tracking changes on multiple files, not only application.css

### ISSUE THREAD

**Issue by loqimean** [rails/propshaft#82]
Houston we have a problem). Hi guys, I have trouble with using many CSS files in the folder `app/assets/stylesheets`, like when I add a file like `buttons.css` and load it to the `application.css` by `@import url('buttons.css');` that is done, but.. when I make changes inside file `buttons.css` - no changes on-site, I mean that changes, not tracks or maybe I do something wrong. Can you help me please with it?

**Comment by brenogazzola** [comment]
1 - Which css gem are you using: cssbundling-rails, dart-sass or tailwind-rails?

2 - Do you have a process running to watch the files and recompile when changing?

3 - Do changes in application.css work at least?

**Comment by loqimean** [comment]
> 1 - Which css gem are you using: cssbundling-rails, dart-sass or tailwind-rails?
> 
> 2 - Do you have a process running to watch the files and recompile when changing?
> 
> 3 - Do changes in application.css work at least?

1 - tailwindcss-rails
2 - what do you mean? like `bin/dev`?
3 - yeah, changes copiles of course in this file, 'cause I attached it to `application.html.erb` in `stylesheets_pack_tag`, even if I attach file `buttons.css` (I mean by tag `stylesheets_pack_tag`) changes tracks too

**Comment by brenogazzola** [comment]
Yes, `bin/dev`. The `tailwindcss-rails` creates a Procfile that includes the watcher process:
```
web: bin/rails server -p 3000
css: bin/rails tailwindcss:watch
```

So, the usual "flow" is:
1 - You change `app/assets/stylesheets/application.tailwind.css`
2 - The watcher process noticed the changes, recompiles and places the file in `app/assets/builds/tailwind.css`
3 - Propshafts notices that the file it was tracking (`app/assets/builds/tailwind.css`) changed, so it reloads that file
4 - The changes become visible on the next page reload.

So, what I think is happening is that when you change the `buttons.css` file, instead of the `application.tailwind.css` file, the tailwind watcher is not noticing the change, and thus not recompiling.

Could you please test the following?
1 - Stop `./bin/dev`
2 - Delete `app/assets/builds/tailwind.css`
3 - Run `./bin/dev`
4 - Check `app/assets/builds/tailwind.css` exists
5 - Change `button.css`
6 - Check if the change is reflected in `app/assets/builds/tailwind.css`.

Is the answer to 6 is "No", then this is a problem in the tailwind gem and it's better if we move this discussion there.

**Comment by loqimean** [comment]
> 

answer to 6 is "No" for my bad(, it's not to change this file, it's even just not load the file to the site

**Comment by loqimean** [comment]
> Yes, `bin/dev`. The `tailwindcss-rails` creates a Procfile that includes the watcher process:
> 
> ```
> web: bin/rails server -p 3000
> css: bin/rails tailwindcss:watch
> ```
> 
> So, the usual "flow" is: 1 - You change `app/assets/stylesheets/application.tailwind.css` 2 - The watcher process noticed the changes, recompiles and places the file in `app/assets/builds/tailwind.css` 3 - Propshafts notices that the file it was tracking (`app/assets/builds/tailwind.css`) changed, so it reloads that file 4 - The changes become visible on the next page reload.
> 
> So, what I think is happening is that when you change the `buttons.css` file, instead of the `application.tailwind.css` file, the tailwind watcher is not noticing the change, and thus not recompiling.
> 
> Could you please test the following? 1 - Stop `./bin/dev` 2 - Delete `app/assets/builds/tailwind.css` 3 - Run `./bin/dev` 4 - Check `app/assets/builds/tailwind.css` exists 5 - Change `button.css` 6 - Check if the change is reflected in `app/assets/builds/tailwind.css`.
> 
> Is the answer to 6 is "No", then this is a problem in the tailwind gem and it's better if we move this discussion there.

answer to 6 is "No" for my bad(, it's not to change this file, it's even just not load the file to the site

**Comment by brenogazzola** [comment]
@loqimean Do you think you can provide me with a minimal project that demonstrates the problem? I'll debug it and figure out where the problem is.

**Comment by loqimean** [comment]
> @loqimean Do you think you can provide me with a minimal project that demonstrates the problem? I'll debug it and figure out where the problem is.

okay, I will tag you when it's will be done

**Comment by dhh** [comment]
Reopen when you have a reproducible setup.
