### ISSUE TITLE
Generating GZip and Brotli compressed versions of assets

### ISSUE THREAD

**Issue by mudge** [rails/propshaft#86]
In migrating from [Sprockets](https://github.com/rails/sprockets) to a Propshaft + [JavaScript Bundling](https://github.com/rails/jsbundling-rails/) and [CSS Bundling for Rails](https://github.com/rails/cssbundling-rails/) set up, we have lost the generation of `.gz` compressed versions of our JavaScript and CSS assets (see [Sprockets' `ZlibExporter`](https://github.com/rails/sprockets/blob/2c38d99930421c22896a65e1d384edf90830f4c3/lib/sprockets/exporters/zlib_exporter.rb)).

As these files would automatically be served by the [`ActionDispatch::Static`](https://github.com/rails/rails/blob/61d6eb119fc53678d8f5028bd73ae77e69b91fb6/actionpack/lib/action_dispatch/middleware/static.rb) middleware (useful when serving Rails applications from [Heroku](https://heroku.com)), would adding similar functionality to Propshaft be welcome or is it out of scope for the project?

I'd imagine it would be an optional part of [outputting the assets in the Processor](https://github.com/rails/propshaft/blob/f9e8c3b1f7f9d9265ac10c80d0bd6d8ee6127793/lib/propshaft/processor.rb#L16), creating versions of each compressable asset with the same filename but with `.gz` and `.br` appended.

**Comment by rafaelfranca** [comment]
In the Propshaft setup, it is the job of the JavaScript/css bundling tool to generate the compressed version of the assets. Propshaft should copy them, and keep the digest, but I don't think it should compress.

Of course the problem is that in the current implementation, Propshaft modify CSS files to change the image paths, the compressed version would be incorrect.

If we implement compression on Propshaft I don't think there is any feature that Sprockets had that Propshaft doesn't have, so I don't see the point of implementing a new library.

**Comment by mudge** [comment]
Thanks, @rafaelfranca.

To ensure I understand:

* Ideally, it is the responsibility of the JavaScript and CSS bundling tool to generate compressed versions of assets in `app/assets/builds` which Propshaft would then copy and digest appropriately

* However, this would break CSS files that load relative URLs, e.g. background images, as they need their paths updating to the digested version (e.g. `my-image-8ec6a47d28e43287bbe86c88ca83468d728ac84a.jpg`) and Propshaft will not update any compressed CSS files (as they will be opaque `.gz` and `.br` files rather than `.css` which would need decompressing and recompressing)

As for the scope creep of Propshaft vs Sprockets: is there an argument here that this still maintains Propshaft's strict delegation of compiling/bundling assets (viz. you should still use JavaScript and CSS Bundling for Rails to compile your assets with Sass, Tailwind, esbuild, Webpack, etc.) but the compression of copied, digested assets is an acceptable responsibility as it requires knowledge of the final version of the assets, something only Propshaft knows?

**Comment by brenogazzola** [comment]
Early versions of Propshaft had brotli compression by default. This was removed when we noticed that CDNs provide this feature on their free plans, and are capable of doing feature detection to decide if they should serve gzip or brotli.

Propshaft delegates to CDNs the responsibility of compressing files.

**Comment by nickjj** [comment]
> Propshaft delegates to CDNs (or NGINX) the responsibility of compressing files.

NGINX has a cost to do compression since it takes CPU time to do compression on the fly, especially if it's maxed out. This is objectively worse than having your digester compress the files for you beforehand, then you can configure NGINX to say the files are already compressed and serve them as they are without compute time.

Tools like Tailwind and esbuild do not compress files either which leaves performing this action up to the user. That means every user will need to invent their own way to do this and also apply it to for every deployment. Would it be fair to say this goes against the grain of what Rails tries to provide?

Just throwing this out there to maybe reconsider adding compression support.
