### ISSUE TITLE
propshaft + ViewComponents + Stimulus

### ISSUE THREAD

**Issue by edugonch** [rails/propshaft#87]
Is there a way to configure propshaft with Stimulus controllers in the ViewComponents (https://viewcomponent.org/) components folder instead of the javascript folder? I try the assets pipline aproach (https://github.com/github/view_component/issues/1064) but didn't work.

**Comment by brenogazzola** [comment]
I’ll need more information on what’s going wrong to help you. Are the files you need not placed in the public folder? Are files there but not found?

Propshaft is only responsible for moving files from their source directories to the public folder. This means that as long as all folders containing files you need are in the paths array, they will be moved too.

**Comment by asip** [comment]
@edugonch

https://github.com/github/view_component/issues/168
https://github.com/palkan/view_component-contrib

I think that your faced problem isn’t related to propshaft.

What about using sprockets instead of propshaft?

**Comment by edugonch** [comment]
@asip you are right, I'm complicated too much just to handle the assets, I'll just continue with sprockets.

**Comment by asip** [comment]
@edugonch 

I'm using Stimulus + ViewComponents in my study.
The study uses sprockets or propshaft  to handle the assets. 

For your reference.

sprockets:
https://github.com/asip/easel
propshaft:
https://github.com/asip/easel/tree/switch_from_sprockets_to_propshaft

**Comment by edugonch** [comment]
@asip thank you, I apreciate it, I'll take a look.

**Comment by lockemx** [comment]
I can describe something that works. With the asset pipeline approach with sprockets, the solutions generally seem to be working around an issue with assets being collected without preserving the components prefix.  With propshaft and importmap, you avoid the issue when you use relocate components to an "app/frontend/" directory and look for assets starting there. You can change `config.view_component.view_component_path` as well so that generators place new files there. I tested this with Rails 7 and the sidecar and stimulus options for view_component generation. The following shows what lines need to be added to existing or new files.

`config/application.rb`
```
    config.autoload_paths << Rails.root.join("app/frontend/components")
    config.importmap.cache_sweepers << Rails.root.join("app/frontend")
    config.assets.paths << Rails.root.join("app/frontend")
    config.view_component.view_component_path = "app/frontend/components"
```

`config/importmap.rb`
```
pin_all_from "app/frontend/components", under: "components"
```

`app/frontend/components/index.js`
```
import { application } from "controllers/application"

import { lazyLoadControllersFrom } from "@hotwired/stimulus-loading"
lazyLoadControllersFrom("components", application)
```

`app/javascript/application.js`
```
import "components"
```

**Comment by lockemx** [comment]
I can describe something that works with propshaft and importmap in Rails 7. I think it's best to have propshaft pick up assets stimulus controllers with the components directory / prefix still intact. This should be done without starting to look for assets at the app directory. Stimulus controllers all need to end up under the controllers prefix after they are mapped by importmap so that they can be eager or lazy loaded them together as is normally done in controllers/index.js. I include the config option that tells the view_component generator of the new app/frontend/components location. I think more tweaking could be done to make the controller reference in data-controller shorter when pointing to a controller in a sidecar. I tested this with Rails 7 with and without the sidecar and stimulus options on view_component generation. The following shows what lines need to be added to existing or new files.

`config/application.rb`
```ruby
    config.autoload_paths << Rails.root.join("app/frontend/components")
    config.importmap.cache_sweepers << Rails.root.join("app/frontend")
    config.assets.paths << Rails.root.join("app/frontend")
    config.view_component.view_component_path = "app/frontend/components"
```

`config/importmap.rb`
```ruby
pin_all_from "app/frontend/components", under: "controllers", to: "components"
```

Reminder: The entire app/components directory needs to be moved to app/frontend/components.

**Comment by theo-bittencourt** [comment]
@lockemx Your approach worked for me. It's more straightforward than rake approach from ViewComponent/view_component#1064. 

But cannot figure out why just `app/components` didn't work here.
