### ISSUE TITLE
Propshaft Rails - Best practices on how to load multiple files. [question]

### ISSUE THREAD

**Issue by equivalent** [rails/propshaft#95]
I'm playing around with Propshaft for couple of days now and I love it. I just want to be sure the way I'm using it is aligned with vision for Propshaft.

### Question1 - is it ok to load multiple CSS via stylesheet_link_tag 

Let say I need to load several vendor CSS files and several custom CSS files. I find it that the best way for me is to add multiple  `stylesheet_link_tag`:

```
// app/views/layouts/application.css
<head>
    <%= stylesheet_link_tag "simplebar.min.css", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "leaflet.css", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "tiny-slider.css", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "nouislider.min.css", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "theme.min.css", "data-turbo-track": "reload" %> 

    <%= stylesheet_link_tag "trix", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "actiontext", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "rails_bootstrap_forms", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "my_other_custom.css", "data-turbo-track": "reload" %>
</head>
```

Is this considered ok/best-practice? Or would you suggest something else?

> note I find it to import files from css with `import url('/some-other.css')` possible but problematic (more info [here](https://github.com/rails/propshaft/issues/90)). 

### Question2 - load all CSS every-time or load particular context CSS ?

Hypothetically if  my project ends up with 50 vendor CSS files and 17 css files. Is it ok to load all 67  at once in application layout (as described in Question1) or is it better to load them in different contexts. e.g.:

```
// app/views/layouts/application.css
<head>
    <!-- some core CSS -->
    <%= yield :head %>
    <%= stylesheet_link_tag "theme.min.css", "data-turbo-track": "reload" %> 
    <%= stylesheet_link_tag "rails_bootstrap_forms", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
</head>
...
```

```
//app/views/posts/_form
....
<% content_for :head do %>
    <%= stylesheet_link_tag "trix", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "actiontext", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "my_other_custom.css", "data-turbo-track": "reload" %>

<% end %>
```

Although the second option makes theoretically more sense, especially for custom app css (no need to load marketing CSS everywhere),  but when it comes to vendor CSS files is it worth the trouble ?

 If I understand correctly all the CSS is cached in the browser  = so it should not be a big deal. Any opinion on this ?

### Question 3 - should developers try to group application CSS to few larger files or are lot of smaller files ok ?

which one you think is better for best practice:

Option A - Lot of smaller app files example : 

```
// app/views/layouts/application.css
<head>
   ...
    <%= stylesheet_link_tag "frontpage.css", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "posts.css", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "publishing.css", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "comments.css", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "author.css", "data-turbo-track": "reload" %>
</head>
```

Option B - try to group them to one bigger CSS file: 

```
// app/views/layouts/application.css
<head>
   ...
    <%= stylesheet_link_tag "frontpage.css", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "blog.css", "data-turbo-track": "reload" %>
</head>
```

### question 4 - is loading JavaScript via Propshaft bad idea?

yes ideally I should use importmaps to load my JS 

BUT  let say I'm working with one of bootstrap-themes (e.g.: [Front](https://htmlstream.com/preview/front-v4.2/html/documentation/index.html)). Once I download the theme I got bunch of vendor javascript files that I can just move to `vendor/assets/javascript/` and load with `javascript_include_tag` 

```
<body>
    ...
  
    <%= javascript_include_tag 'theme.min.js', defer: true %>
    <%= javascript_include_tag "tom-select.complete.min.js", defer: true %>
     ....
<body>
```

I find it really convenient  and not colliding  with my importmaps JS (Stimulus, Turbo, all works nice)

Is this considered OK ?

 

Thank you for your input

> P.S. sorry I'm posting this question here, I tried to ask this on discuss.rubyonrails.org but spam filter marked [my post](https://discuss.rubyonrails.org/t/propshaft-rails-best-practices-on-how-to-load-multiple-css-files/80630/1) as spam 🙄

**Comment by brenogazzola** [comment]
Your questions are not Propshaft related. You could ask the same things if you were using Sprockets or Import Maps. They are more along the lines of "What are the best practices for serving CSS and JS files?"

The answers will depend on how your users are accessing your app. If they are all on fast broadband connections, and powerful desktops or current gen iPhones/Androids, then there won't be much difference between any of the options you mentioned. However if you have people on older phones or slow connections, then it all boils down to this: serve the least amount of CSS possible on the first page load, since CSS is a render blocking resource, and your users will start leaving if that blank page lasts for more than a moment.

**Questions 1 & 3:**
If your CDN supports HTTP2, many small files are fine. If not, you should stick to bundling everything in a single file.

**Question 2:**
Neither extremes. Create a layout file for your landing pages that only loads the CSS needed to render them. Create another layout that contains everything. This should have the most impact for the least effort.

**Question 4:**
I don't use import maps so I can tell you from experience that it's fine, but I see no reason why it wouldn't. You have to remember that in production, after the HTML is generated, Propshaft's job is done. Actually serving the file is up to Puma or the CDN.

**Comment by equivalent** [comment]
Thank you @brenogazzola for answering this, much appreciated ❤️  

All your points make sense. Just one thing I want to address:

> Your questions are not Propshaft related. You could ask the same things if you were using Sprockets or Import Maps. They are more along the lines of "What are the best practices for serving CSS and JS files?"

I see. Yes, very true. My thinking process around asking these questions was set to mindset:  Sprockets == bundling multiple CSS files to one,  Propshaft has no bundle process now what ?  ...therefore I thought I'm missing some Propshaft's overall strategy. But now I see: Propshaft serves as a tool towards the best practices of HTTP2 🤔 👍   (now that I think about it it was mentioned zillion  times in [DHH's Propshaft podcast](https://rubyrogues.com/propshaft-with-david-heinemeier-hansson-dhh-ruby-542))


-------------

Let me just add one more note to your point for people googling this:

> If your CDN supports HTTP2

this is a great point, I keep on forgetting this. (for example Heroku don't support HTTP2 ([source](https://devcenter.heroku.com/articles/http-routing#http-versions-supported)) but workaround is placing the app in front of [cloudflare](https://www.cloudflare.com/) ...or use CDN that supports HTTP2 for assets `config.asset_host = "http://assets.mycdn.com"`

**Comment by brenogazzola** [comment]
You can pair Propshaft with cssbundling-rails and jsbundling-rails to get file bundling and transpiling working. It’s what I do, since I still prefer having a single CSS and a single JS per page (though I actually have some 8 CSS files and 6+ JS files as they are used in specific areas like I advised you to do for question 3)
